const bearer ='eyJhbGciOiJSUzI1NiIsImtpZCI6IjVGQUQ4RTE5MjMwOURFRUJCNzBCMzU5M0E2MDU3OUFEMUM5NjgzNDkiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJYNjJPR1NNSjN1dTNDeldUcGdWNXJSeVdnMGsifQ.eyJuYmYiOjE2OTEwMTc0NDAsImV4cCI6MTY5MTEwMzg0MCwiaXNzIjoiaHR0cHM6Ly9vYXV0aC5mYXRzZWNyZXQuY29tIiwiYXVkIjoicHJlbWllciIsImNsaWVudF9pZCI6ImFhOTFhY2E0YzUzMjQ2MTJhYTRhZGMwNWI0NTEzZmNkIiwic2NvcGUiOlsicHJlbWllciJdfQ.IZyx2d7uSbxB3g9rdBDTj1lJW6X_N2VIsZNZqk8_qx4fF2xtXs41inGOZhia7Pp3Xj-yNpBnemD7BwCkFEVJtA-W_y5mV2PfoAO4GVCQi7JPQd6jMJZD3FaiKmPSvNoUY5oX1zzMIG8r9s_UFsTfssSnQf4nar5xMu5BhI2FNzbxvWTn5xLeiDigorsGOdqIV_8looZBe0VwNhLSydSIBpP7LpyMvQbhFrISxmUqI3M5EegMvpiZ7b410pU6Y5CbyH-3rICeydpCJ-Y4euT4BgdW_hKqR-IMEh2z5B3wE_uMX5YA8tvfJ7n0mDgy7W4FZx-_kWELgUUiqvX-brIwdw';

const pathSearch = 'https://platform.fatsecret.com/rest/server.api?method=foods.search.v2&search_expression=a&format=json&max_results=50&flag_default_serving=true&page_number=1';

const obj = {
    token:bearer,
    path:pathSearch
}

module.exports = obj;